{
  "formatVersion": "1.1",
  "component": {
    "group": "com.group.base.entity",
    "module": "library_common_data",
    "version": "0.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "library_common_data-0.0.1.jar",
          "url": "library_common_data-0.0.1.jar",
          "size": 80115,
          "sha512": "bd3dcf80f187827e93e2984334605126b6d1ce5b107d962dfd320530e34b263b7528e90045e8ea0b5c34dc6d46d1f94505210efd15d0f5bb002124ad02c3bf60",
          "sha256": "df96843b2077464e1a33cda80a70a267c99e1f32f05119e57cb8f18745a7297d",
          "sha1": "554d9b63449e71d625c1edbb7022f6bd3e5dd4f9",
          "md5": "ad5d188154e79afd230e83254cc2920b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "library_common_data-0.0.1.jar",
          "url": "library_common_data-0.0.1.jar",
          "size": 80115,
          "sha512": "bd3dcf80f187827e93e2984334605126b6d1ce5b107d962dfd320530e34b263b7528e90045e8ea0b5c34dc6d46d1f94505210efd15d0f5bb002124ad02c3bf60",
          "sha256": "df96843b2077464e1a33cda80a70a267c99e1f32f05119e57cb8f18745a7297d",
          "sha1": "554d9b63449e71d625c1edbb7022f6bd3e5dd4f9",
          "md5": "ad5d188154e79afd230e83254cc2920b"
        }
      ]
    }
  ]
}
